package alpvax.abilities.core;

import alpvax.abilities.api.capabilities.CapabilityAbilityHandler;
import alpvax.abilities.core.proxy.CommonProxy;
import net.minecraft.client.resources.I18n;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = AbilitiesAPIConstants.MOD_ID, name = AbilitiesAPIConstants.MOD_NAME)
public class AbilityMod
{
	@SidedProxy(clientSide = "alpvax.abilities.core.proxy.ClientProxy", serverSide = "alpvax.abilities.core.proxy.CommonProxy")
	public static CommonProxy proxy;

	@Mod.Instance(AbilitiesAPIConstants.MOD_ID)
	public static AbilityMod instance;

	@Metadata(AbilitiesAPIConstants.MOD_ID)
	public static ModMetadata meta;

	//public static AlpPacketManager packetHandler;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.authorList.add("Alpvax");
		meta.description = I18n.format("mod.abilities.description");
		meta.autogenerated = false;

		CapabilityAbilityHandler.registerCapabilities();
		MinecraftForge.EVENT_BUS.register(new AbilityAPIHooks());

		/*TODO:packetHandler = new AlpPacketManager(AbilitiesAPIConstants.MOD_ID); initPackets();
		}
		
		private void initPackets()
		{
		//TODO: packetHandler.registerMessage(PoweredPlayerPacket.Handler.class, PoweredPlayerPacket.class, Side.CLIENT);*/
	}
}