package alpvax.racemod.core;

import alpvax.racemod.core.proxy.CommonProxy;
import net.minecraft.client.resources.I18n;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = RaceModConstants.MOD_ID, name = RaceModConstants.MOD_NAME)
public class RaceAndRoleMod
{
	@SidedProxy(clientSide = "alpvax.racemod.core.proxy.ClientProxy", serverSide = "alpvax.racemod.core.proxy.CommonProxy")
	public static CommonProxy proxy;

	@Mod.Instance(RaceModConstants.MOD_ID)
	public static RaceAndRoleMod instance;

	@Metadata(RaceModConstants.MOD_ID)
	public static ModMetadata meta;

	//public static AlpPacketManager packetHandler;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.authorList.add("Alpvax");
		meta.description = I18n.format("mod.racemod.description");
		meta.autogenerated = false;

		CapabilityRaceHandler.register();
		MinecraftForge.EVENT_BUS.register(new RaceModHooks());

		/*TODO:packetHandler = new AlpPacketManager(AbilitiesAPIConstants.MOD_ID); initPackets();
		}
		
		private void initPackets()
		{
		//TODO: packetHandler.registerMessage(PoweredPlayerPacket.Handler.class, PoweredPlayerPacket.class, Side.CLIENT);*/
	}
}
