package alpvax.skillsandabilities.core;

import alpvax.skillsandabilities.capabilities.CapabilityCharacterHandler;
import alpvax.skillsandabilities.core.proxy.CommonProxy;
import net.minecraft.client.resources.I18n;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = CharacterModConstants.MOD_ID, version = CharacterModConstants.MOD_VERSION)
public class CharacterMod
{
	@SidedProxy(
			clientSide = "alpvax.skillsandabilities.core.proxy.ClientProxy",
			serverSide = "alpvax.skillsandabilities.core.proxy.CommonProxy")
	public static CommonProxy proxy;

	@Mod.Instance(CharacterModConstants.MOD_ID)
	public static CharacterMod instance;

	@Metadata(CharacterModConstants.MOD_ID)
	public static ModMetadata meta;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		meta.name = I18n.format("mod." + CharacterModConstants.MOD_ID + ".name");
		meta.description = I18n.format("mod." + CharacterModConstants.MOD_ID + ".description");
		meta.authorList.add("Alpvax");
		meta.autogenerated = false;
		CapabilityCharacterHandler.registerCapabilities();
		MinecraftForge.EVENT_BUS.register(new CharacterModHooks());
	}
}
